name: Dockerized Tests

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  all-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run tests in docker container
        run:  make docker-test-all

      - name: Upload unit test coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out
          parallel: true

      - name: Upload integration test coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: icover.out
          parallel: true

      - name: Generate coverage badge
        uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
